S=./axi_to_char_stream/Makefile
cp $S ./axi_to_multi_stream/Makefile
cp $S ./axi_to_stream/Makefile
cp $S ./stream_combine/combine_lsb/Makefile
cp $S ./stream_combine/combine_msb/Makefile
cp $S ./stream_combine/first_as_lsb/Makefile
cp $S ./stream_combine/first_as_msb/Makefile
cp $S ./stream_discard/discard_array/Makefile
cp $S ./stream_discard/discard_one_stream/Makefile
cp $S ./stream_discard/discard_share_e/Makefile
cp $S ./stream_dup/Makefile
cp $S ./stream_n_to_one/load_balance/Makefile
cp $S ./stream_n_to_one/load_balance_type/Makefile
cp $S ./stream_n_to_one/round_robin/Makefile
cp $S ./stream_n_to_one/round_robin_type/Makefile
cp $S ./stream_n_to_one/tag_select/Makefile
cp $S ./stream_n_to_one/tag_select_type/Makefile
cp $S ./stream_one_to_n/load_balance/Makefile
cp $S ./stream_one_to_n/load_balance_type/Makefile
cp $S ./stream_one_to_n/round_robin/Makefile
cp $S ./stream_one_to_n/round_robin_type/Makefile
cp $S ./stream_one_to_n/tag_select/Makefile
cp $S ./stream_one_to_n/tag_select_type/Makefile
cp $S ./stream_reorder/Makefile
cp $S ./stream_shuffle/Makefile
cp $S ./stream_split/split_lsb/Makefile
cp $S ./stream_split/split_msb/Makefile
cp $S ./stream_sync/Makefile
cp $S ./stream_to_axi/Makefile
cp $S ./uram_array/Makefile
